"""add processed_source to jobs

Revision ID: 40df68c92ea7
Revises: e914d9978aea
Create Date: 2026-08-28 08:27:39.999696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40df68c92ea7'
down_revision = 'e914d9978aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_source', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite recreates the whole table to drop a column, which fails
    # against this project's enforced FK constraints (photo_items/
    # photo_sheet_items reference jobs.id) unless the pragma is
    # toggled off first - same fix as e914d9978aea's downgrade, and
    # the same reason (SQLite treats the pragma as a no-op inside an
    # already-open transaction). Unlike that migration, this one has
    # no data-migration step before it, so there's nothing guaranteeing
    # a transaction is open when we get here. conn.in_transaction()
    # is NOT a reliable guard for this - tested and confirmed it can
    # return True (matching SQLAlchemy's own bookkeeping) while the
    # underlying sqlite3 driver reports no transaction is active, since
    # this migration context runs in "non-transactional DDL" mode where
    # the two can disagree. Only a live COMMIT attempt tells the truth,
    # so swallow the specific "no transaction is active" error instead.
    conn = op.get_bind()
    try:
        conn.exec_driver_sql("COMMIT")
    except sa.exc.OperationalError as exc:
        if "no transaction is active" not in str(exc):
            raise
    conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('processed_source')
    conn.exec_driver_sql("PRAGMA foreign_keys=ON")

    # ### end Alembic commands ###
