"""add rotated_at to secret_code and code_used to jobs

Revision ID: 60746515c4a3
Revises: c1166b40ce8b
Create Date: 2026-08-28 20:08:52.369146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60746515c4a3'
down_revision = 'c1166b40ce8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_used', sa.String(length=4), nullable=True))

    with op.batch_alter_table('secret_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # secret_code has no FK relationships, so its own column drop needs
    # no special handling. jobs, though, is FK-referenced by photo_items/
    # photo_sheet_items and carries its own self-referential reprint_of
    # FK - SQLite batch mode recreates the whole table for ANY column
    # drop, which fails against those constraints unless the pragma is
    # toggled off first. Same pattern as every prior migration that
    # drops a jobs column this session (e.g. c1166b40ce8b).
    with op.batch_alter_table('secret_code', schema=None) as batch_op:
        batch_op.drop_column('rotated_at')

    conn = op.get_bind()
    try:
        conn.exec_driver_sql("COMMIT")
    except sa.exc.OperationalError as exc:
        if "no transaction is active" not in str(exc):
            raise
    conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('code_used')
    conn.exec_driver_sql("PRAGMA foreign_keys=ON")
