"""add photo_sheets and photo_sheet_items

Revision ID: 8440524b9a5b
Revises: ab2a317650f3
Create Date: 2026-08-24 02:02:44.370061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8440524b9a5b'
down_revision = 'ab2a317650f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('sheet_number', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('margin_px', sa.Integer(), nullable=False),
    sa.Column('rendered_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_sheets_batch_id'), ['batch_id'], unique=False)

    op.create_table('photo_sheet_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('size_name', sa.String(length=16), nullable=False),
    sa.Column('x_px', sa.Integer(), nullable=False),
    sa.Column('y_px', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('rotated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['photo_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_sheet_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_sheet_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_sheet_items_sheet_id'), ['sheet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_sheet_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_sheet_items_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_photo_sheet_items_job_id'))

    op.drop_table('photo_sheet_items')
    with op.batch_alter_table('photo_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_sheets_batch_id'))

    op.drop_table('photo_sheets')
    # ### end Alembic commands ###
