"""add orientation margin print_quality to jobs

Revision ID: a7aab2ad81db
Revises: 60746515c4a3
Create Date: 2026-08-29 02:31:09.636203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7aab2ad81db'
down_revision = '60746515c4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('margin', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('print_quality', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # jobs is FK-referenced by photo_items/photo_sheet_items and carries
    # its own self-referential reprint_of FK - SQLite batch mode
    # recreates the whole table for ANY column drop, which fails against
    # those constraints unless the pragma is toggled off first. Same
    # pattern as every prior migration that drops a jobs column
    # (e.g. 60746515c4a3).
    conn = op.get_bind()
    try:
        conn.exec_driver_sql("COMMIT")
    except sa.exc.OperationalError as exc:
        if "no transaction is active" not in str(exc):
            raise
    conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('print_quality')
        batch_op.drop_column('margin')
        batch_op.drop_column('orientation')
    conn.exec_driver_sql("PRAGMA foreign_keys=ON")
