"""initial schema: jobs, photo_items, pricing_rates, secret_code

Revision ID: ab2a317650f3
Revises: 
Create Date: 2026-08-24 01:35:14.997752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2a317650f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=8), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('service_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('attention_reason', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=True),
    sa.Column('color_mode', sa.String(length=8), nullable=True),
    sa.Column('duplex', sa.Boolean(), nullable=True),
    sa.Column('paper_size', sa.String(length=8), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_active_ticket_unique', ['ticket_number'], unique=True, sqlite_where=sa.text("status IN ('uploaded', 'processing', 'ready_for_review', 'printing')"))
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_ticket_number'), ['ticket_number'], unique=False)

    op.create_table('pricing_rates',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('secret_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('generated_on', sa.Date(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_items_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_items_job_id'))

    op.drop_table('photo_items')
    op.drop_table('secret_code')
    op.drop_table('pricing_rates')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index('ix_jobs_active_ticket_unique', sqlite_where=sa.text("status IN ('uploaded', 'processing', 'ready_for_review', 'printing')"))

    op.drop_table('jobs')
    # ### end Alembic commands ###
