"""add reprint_of and reprint_reason to jobs

Revision ID: c1166b40ce8b
Revises: 40df68c92ea7
Create Date: 2026-08-28 14:37:48.320039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1166b40ce8b'
down_revision = '40df68c92ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Two adjustments from the autogenerated version, both confirmed
    # necessary by testing (the autogenerated form failed the UPGRADE
    # itself, not just the downgrade):
    # 1. An explicit constraint name - SQLite's batch mode raises
    #    "Constraint must have a name" for a self-referential FK
    #    created without one.
    # 2. The FK-pragma-toggle guard, normally only needed on a downgrade
    #    that drops a column. ADDING this FK also makes batch mode
    #    recreate the whole jobs table (any constraint change does, not
    #    just a column drop) - and jobs is referenced by photo_items/
    #    photo_sheet_items, so the same "FOREIGN KEY constraint failed
    #    on DROP TABLE jobs" failure this project has hit before on a
    #    downgrade shows up here on the upgrade instead.
    conn = op.get_bind()
    try:
        conn.exec_driver_sql("COMMIT")
    except sa.exc.OperationalError as exc:
        if "no transaction is active" not in str(exc):
            raise
    conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reprint_of', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reprint_reason', sa.String(length=24), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_reprint_of'), ['reprint_of'], unique=False)
        batch_op.create_foreign_key('fk_jobs_reprint_of_jobs', 'jobs', ['reprint_of'], ['id'])
    conn.exec_driver_sql("PRAGMA foreign_keys=ON")

    # ### end Alembic commands ###


def downgrade():
    # SQLite recreates the whole table to drop a column, which fails
    # against this project's enforced FK constraints (photo_items/
    # photo_sheet_items reference jobs.id, and reprint_of is now a
    # self-referential FK on jobs itself) unless the pragma is toggled
    # off first - same pattern as every prior migration that drops a
    # jobs column this session. conn.in_transaction() proved unreliable
    # here in an earlier migration (40df68c92ea7) - a live COMMIT
    # attempt, with the specific "no transaction is active" error
    # swallowed, is the only guard that actually held up under testing.
    conn = op.get_bind()
    try:
        conn.exec_driver_sql("COMMIT")
    except sa.exc.OperationalError as exc:
        if "no transaction is active" not in str(exc):
            raise
    conn.exec_driver_sql("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_reprint_of_jobs', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_reprint_of'))
        batch_op.drop_column('reprint_reason')
        batch_op.drop_column('reprint_of')
    conn.exec_driver_sql("PRAGMA foreign_keys=ON")
