"""add paper_finish and quality to jobs

Revision ID: e914d9978aea
Revises: 8440524b9a5b
Create Date: 2026-08-28 06:59:29.187462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e914d9978aea'
down_revision = '8440524b9a5b'
branch_labels = None
depends_on = None


_PHOTO_SIZES = ("1x1", "2x2", "Passport", "Visa", "Wallet", "4x6", "5x7", "4x4")
_FINISHES = ("glossy", "bond")
_QUALITIES = ("standard", "high")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_finish', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###

    # Data migration: each existing flat photo-size pricing_rates key
    # (e.g. "2x2") becomes 4 composite keys ("2x2-glossy-standard",
    # "2x2-glossy-high", "2x2-bond-standard", "2x2-bond-high"), each
    # seeded from that size's EXISTING price (whatever an admin may
    # have already edited it to, not a hardcoded default) - no price
    # data is lost, all 4 combos just start out finish/quality-neutral
    # until the admin differentiates them from the pricing page.
    # bw_page/color_page are untouched.
    pricing_rates = sa.table(
        "pricing_rates", sa.column("key", sa.String), sa.column("price", sa.Float)
    )
    conn = op.get_bind()
    for size in _PHOTO_SIZES:
        row = conn.execute(
            sa.select(pricing_rates.c.price).where(pricing_rates.c.key == size)
        ).fetchone()
        if row is None:
            continue
        price = row[0]
        for finish in _FINISHES:
            for quality in _QUALITIES:
                conn.execute(
                    pricing_rates.insert().values(key=f"{size}-{finish}-{quality}", price=price)
                )
        conn.execute(pricing_rates.delete().where(pricing_rates.c.key == size))


def downgrade():
    # Reverses the data migration above. Canonical price per size is
    # taken from its {size}-bond-standard combo - an arbitrary but
    # documented choice, since 4 independently-priced combos can't be
    # perfectly inverted back into a single flat price without losing
    # information if an admin has differentiated them by then.
    pricing_rates = sa.table(
        "pricing_rates", sa.column("key", sa.String), sa.column("price", sa.Float)
    )
    conn = op.get_bind()
    for size in _PHOTO_SIZES:
        canonical_key = f"{size}-bond-standard"
        row = conn.execute(
            sa.select(pricing_rates.c.price).where(pricing_rates.c.key == canonical_key)
        ).fetchone()
        price = row[0] if row is not None else None
        for finish in _FINISHES:
            for quality in _QUALITIES:
                conn.execute(
                    pricing_rates.delete().where(
                        pricing_rates.c.key == f"{size}-{finish}-{quality}"
                    )
                )
        if price is not None:
            conn.execute(pricing_rates.insert().values(key=size, price=price))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('quality')
        batch_op.drop_column('paper_finish')

    # ### end Alembic commands ###
